-- MySQL Script generated by MySQL Workbench
-- Wed 17 Jun 2015 20:21:14 EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema relayforlife_kenya
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema relayforlife_kenya
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `relayforlife_kenya` DEFAULT CHARACTER SET utf8 ;
USE `relayforlife_kenya` ;

-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`commitee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`commitee` (
  `commiteeID` INT(11) NOT NULL AUTO_INCREMENT,
  `commitee_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`commiteeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`user` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`order` (
  `orderID` INT(11) NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NOT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `date_ordered` DATE NULL DEFAULT NULL,
  `MPESA_confirmation_code` VARCHAR(45) NULL DEFAULT NULL,
  `user_userID` INT(11) NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_order_user1_idx` (`user_userID` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `relayforlife_kenya`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`team` (
  `teamID` INT(11) NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`teamID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`participant` (
  `participantID` INT(11) NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NOT NULL,
  `teamID` INT(11) NOT NULL,
  `team_teamID` INT(11) NOT NULL,
  PRIMARY KEY (`participantID`),
  INDEX `fk_participant_team1_idx` (`team_teamID` ASC),
  CONSTRAINT `fk_participant_team1`
    FOREIGN KEY (`team_teamID`)
    REFERENCES `relayforlife_kenya`.`team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`product_type` (
  `product_type_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `product_type_name` VARCHAR(45) NULL DEFAULT NULL,
  `product_type_desc` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`product_type_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`product` (
  `productID` INT(11) NOT NULL,
  `product_type_ID` INT(11) NOT NULL,
  `product_name` VARCHAR(45) NULL DEFAULT NULL,
  `unit_price` INT(11) NULL DEFAULT NULL,
  `product_desc` VARCHAR(255) NULL DEFAULT NULL,
  `product_type_product_type_ID` INT(11) NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `fk_product_product_type1_idx` (`product_type_product_type_ID` ASC),
  CONSTRAINT `fk_product_product_type1`
    FOREIGN KEY (`product_type_product_type_ID`)
    REFERENCES `relayforlife_kenya`.`product_type` (`product_type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`products_ordered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`products_ordered` (
  `products_ordered_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `orderID` INT(11) NOT NULL,
  `productID` INT(11) NOT NULL,
  `product_quantity` INT(11) NULL DEFAULT NULL,
  `order_orderID` INT(11) NOT NULL,
  `product_productID` INT(11) NOT NULL,
  PRIMARY KEY (`products_ordered_ID`),
  INDEX `fk_products_ordered_order1_idx` (`order_orderID` ASC),
  INDEX `fk_products_ordered_product1_idx` (`product_productID` ASC),
  CONSTRAINT `fk_products_ordered_order1`
    FOREIGN KEY (`order_orderID`)
    REFERENCES `relayforlife_kenya`.`order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_ordered_product1`
    FOREIGN KEY (`product_productID`)
    REFERENCES `relayforlife_kenya`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`user_address` (
  `user_address_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city_village` VARCHAR(255) NULL DEFAULT NULL,
  `county` VARCHAR(50) NULL DEFAULT NULL,
  `postal_code` VARCHAR(50) NULL DEFAULT NULL,
  `user_userID` INT(11) NOT NULL,
  PRIMARY KEY (`user_address_ID`),
  INDEX `fk_user_address_user1_idx` (`user_userID` ASC),
  CONSTRAINT `fk_user_address_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `relayforlife_kenya`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`user_details` (
  `user_name_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `UserID` INT(11) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `mobile_no` VARCHAR(45) NULL DEFAULT NULL,
  `next_of_kin_firstname` VARCHAR(45) NULL DEFAULT NULL,
  `next_of_kin_lastname` VARCHAR(45) NULL DEFAULT NULL,
  `next_of_kin_mobileno` VARCHAR(45) NULL DEFAULT NULL,
  `user_userID` INT(11) NOT NULL,
  PRIMARY KEY (`user_name_ID`),
  INDEX `fk_user_details_user1_idx` (`user_userID` ASC),
  CONSTRAINT `fk_user_details_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `relayforlife_kenya`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `relayforlife_kenya`.`volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relayforlife_kenya`.`volunteer` (
  `volunteerID` INT(11) NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NOT NULL,
  `commiteeID` VARCHAR(45) NOT NULL,
  `date_joined` DATE NOT NULL,
  `commitee_commiteeID` INT(11) NOT NULL,
  `user_userID` INT(11) NOT NULL,
  PRIMARY KEY (`volunteerID`),
  INDEX `fk_volunteer_commitee_idx` (`commitee_commiteeID` ASC),
  INDEX `fk_volunteer_user1_idx` (`user_userID` ASC),
  CONSTRAINT `fk_volunteer_commitee`
    FOREIGN KEY (`commitee_commiteeID`)
    REFERENCES `relayforlife_kenya`.`commitee` (`commiteeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_volunteer_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `relayforlife_kenya`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
